CREATE TABLE WORKCAL_TYPE(
        ID VARCHAR(50) NOT NULL,
	NAME VARCHAR(50),
        CONSTRAINT PK_WORKCAL_TYPE PRIMARY KEY(ID)
);

CREATE TABLE WORKCAL_RULE(
        ID VARCHAR(50) NOT NULL,
	YEAR INT,
        WEEK INT,
	NAME VARCHAR(50),
	WORK_DATE TIMESTAMP,
	STATUS INT,
	TYPE_ID BIGINT,
        CONSTRAINT PK_WORKCAL_RULE PRIMARY KEY(ID),
	CONSTRAINT FK_WORKCAL_RULE_TYPE FOREIGN KEY(
ID) REFERENCES WORKCAL_TYPE(ID)
);

CREATE TABLE WORKCAL_PART(
        ID VARCHAR(50) NOT NULL,
        SHIFT INT,
	START_TIME VARCHAR(5),
	END_TIME VARCHAR(5),
	RULE_ID BIGINT,
        CONSTRAINT PK_WORKCAL_PART PRIMARY KEY(ID),
	CONSTRAINT FK_WORKCAL_PART_RULE FOREIGN KEY(
ID) REFERENCES WORKCAL_RULE(ID)
);