--------------------------------------------------------
--  文件已创建 - 星期三-九月-24-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOXBPM_WORKCAL_TYPE
--------------------------------------------------------

  CREATE TABLE "FOXBPM"."FOXBPM_WORKCAL_TYPE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOXBPM_WORKCAL_PART
--------------------------------------------------------

  CREATE TABLE "FOXBPM"."FOXBPM_WORKCAL_PART" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SHIFT" NUMBER(*,0), 
	"START_TIME" VARCHAR2(5 BYTE), 
	"END_TIME" VARCHAR2(5 BYTE), 
	"RULE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOXBPM_WORKCAL_RULE
--------------------------------------------------------

  CREATE TABLE "FOXBPM"."FOXBPM_WORKCAL_RULE" 
   (	"ID" VARCHAR2(50 BYTE), 
	"YEAR" NUMBER(*,0), 
	"WEEK" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"WORK_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(*,0), 
	"TYPE_ID" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FOXBPM.FOXBPM_WORKCAL_TYPE
SET DEFINE OFF;
Insert into FOXBPM.FOXBPM_WORKCAL_TYPE (ID,NAME) values ('AAA','2014年度工作日历');
REM INSERTING into FOXBPM.FOXBPM_WORKCAL_PART
SET DEFINE OFF;
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P1',0,'08:30','12:00','R1');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P2',1,'01:30','05:30','R1');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P3',0,'08:30','12:00','R2');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P4',1,'01:30','05:30','R2');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P5',0,'08:30','12:00','R3');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P6',1,'01:30','05:30','R3');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P7',0,'08:30','12:00','R4');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P8',1,'01:30','05:30','R4');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P9',0,'08:30','12:00','R5');
Insert into FOXBPM.FOXBPM_WORKCAL_PART (ID,SHIFT,START_TIME,END_TIME,RULE_ID) values ('P10',1,'01:30','05:30','R5');
REM INSERTING into FOXBPM.FOXBPM_WORKCAL_RULE
SET DEFINE OFF;
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G1',2014,null,'国庆假期',to_timestamp('01-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G2',2014,null,'国庆假期',to_timestamp('02-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G3',2014,null,'国庆假期',to_timestamp('03-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G4',2014,null,'国庆假期',to_timestamp('04-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G5',2014,null,'国庆假期',to_timestamp('05-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G6',2014,null,'国庆假期',to_timestamp('06-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('G7',2014,null,'国庆假期',to_timestamp('07-10月-14 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),1,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('R1',2014,1,'周一',null,0,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('R2',2014,2,'周二',null,0,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('R3',2014,3,'周三',null,0,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('R4',2014,4,'周四',null,0,'AAA');
Insert into FOXBPM.FOXBPM_WORKCAL_RULE (ID,YEAR,WEEK,NAME,WORK_DATE,STATUS,TYPE_ID) values ('R5',2014,5,'周五',null,0,'AAA');
--------------------------------------------------------
--  DDL for Index PK_WORKCAL_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOXBPM"."PK_WORKCAL_TYPE" ON "FOXBPM"."FOXBPM_WORKCAL_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_WORKCAL_PART
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOXBPM"."PK_WORKCAL_PART" ON "FOXBPM"."FOXBPM_WORKCAL_PART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_WORKCAL_RULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOXBPM"."PK_WORKCAL_RULE" ON "FOXBPM"."FOXBPM_WORKCAL_RULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FOXBPM_WORKCAL_TYPE
--------------------------------------------------------

  ALTER TABLE "FOXBPM"."FOXBPM_WORKCAL_TYPE" ADD CONSTRAINT "PK_WORKCAL_TYPE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FOXBPM"."FOXBPM_WORKCAL_TYPE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOXBPM_WORKCAL_PART
--------------------------------------------------------

  ALTER TABLE "FOXBPM"."FOXBPM_WORKCAL_PART" ADD CONSTRAINT "PK_WORKCAL_PART" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FOXBPM"."FOXBPM_WORKCAL_PART" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOXBPM_WORKCAL_RULE
--------------------------------------------------------

  ALTER TABLE "FOXBPM"."FOXBPM_WORKCAL_RULE" ADD CONSTRAINT "PK_WORKCAL_RULE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FOXBPM"."FOXBPM_WORKCAL_RULE" MODIFY ("ID" NOT NULL ENABLE);
